### ISSUE TITLE
Update the optimist package to mitigate security vulnerability

### ISSUE THREAD

**Issue by Jelle-vz** [agnoster/base32-js#27]
Could you please update (or swap out because of deprecation notice) [optimist](https://www.npmjs.com/package/optimist)?

| Id  |  Module | Title  | Path  |  Sev. | Url |
|---|---|---|---|---|
| 1067342  | minimist  | Prototype Pollution in minimist  | optimist>minimist  | critical  | https://github.com/advisories/GHSA-xvch-5gv4-984h |
|  1070255 |  minimist |  Prototype Pollution in minimist | optimist>minimist  | moderate  | https://github.com/advisories/GHSA-vh95-rmgr-6w4m |

**Comment by agnoster** [comment]
Just pushed a new update replacing optimist with minimist^0.2.6, hopefully that should resolve the issue.

Didn't know anyone was using this package still! 🤣

**Comment by Jelle-vz** [comment]
Haha, nice! Thanks a lot!

**Comment by Jelle-vz** [comment]
Haha, nice! Thanks a lot!
